from typing import Protocol
from .models import OrderRequest, StrategyOrder


class ExecutionAdapter(Protocol):
    async def submit_orders(self, orders: list[OrderRequest]): ...
    async def cancel_orders(self, client_order_ids: list[str]): ...
    async def replace_orders(self, replacements: list[tuple[str, OrderRequest]]): ...
    async def get_open_orders(self) -> list[StrategyOrder]: ...
